FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

WORKDIR /work/
RUN chgrp -R 0 /work && chmod -R g=u /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080 8443 9000
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
