FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /work/
RUN chgrp -R 0 /work && chmod -R g=u /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080 8443 9000
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
