apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-passwords
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swim-ed254-provider-validator.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secret.certsPassword | quote }}
  PROXY_MTLS_KEYSTORE_PASSWORD: {{ .Values.secret.proxyMtlsKeystorePassword | quote }}
  PROXY_MTLS_TRUSTSTORE_PASSWORD: {{ .Values.secret.proxyMtlsTruststorePassword | quote }}
