apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swim-ed254-provider-validator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "swim-ed254-provider-validator.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
  type: ClusterIP
