{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swim-ed254-provider-validator.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: swim-operator
spec:
  selector:
    matchLabels:
      {{- include "swim-ed254-provider-validator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /q/metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
