apiVersion: v1
kind: ConfigMap
metadata:
  name: swim-ed254-provider-validator-config
  labels:
    app: swim-ed254-provider-validator
    app.kubernetes.io/name: swim-ed254-provider-validator
    app.kubernetes.io/component: ed254-provider-validator
    app.kubernetes.io/part-of: swim-ed254
data:
  KEYCLOAK_URL: "https://rhbk.apps.ocp4.masales.cloud"
  KEYCLOAK_REALM: "swim"
  KEYCLOAK_CLIENT_ID: "swim-public-client"
  SWIM_PROVIDER_API_URLS: "https://swim-ed254-provider-swim-sandbox.apps.ocp4.masales.cloud,https://swim-ed254-provider-mtls-swim-sandbox.apps.ocp4.masales.cloud"
  PROXY_MTLS_KEYSTORE_PATH: "/certs/client/keystore.p12"
  PROXY_MTLS_KEYSTORE_TYPE: "PKCS12"
  PROXY_MTLS_TRUSTSTORE_PATH: "/certs/client/truststore.p12"
  PROXY_MTLS_TRUSTSTORE_TYPE: "PKCS12"
  MARIADB_HOST: "swim-ed254-provider-validator-mariadb"
  MARIADB_PORT: "3306"
  MARIADB_DATABASE: "swim_client"
  MARIADB_USERNAME: "swim"
  SWIM_PROVIDER_AMQP_HOST: "swim-ed254-provider-artemis-0.swim-sandbox.svc.cluster.local"
  SWIM_PROVIDER_AMQP_PORT: "5672"
  MARIADB_PASSWORD: "swim"
