apiVersion: v1
kind: Secret
metadata:
  name: swim-ed254-provider-validator-passwords
  labels:
    app: swim-ed254-provider-validator
    app.kubernetes.io/name: swim-ed254-provider-validator
    app.kubernetes.io/component: ed254-provider-validator
    app.kubernetes.io/part-of: swim-ed254
type: Opaque
stringData:
  password: changeit
  PROXY_MTLS_KEYSTORE_PASSWORD: changeit
  PROXY_MTLS_TRUSTSTORE_PASSWORD: changeit
