apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: swim-ed254-provider-validator-metrics
  labels:
    app: swim-ed254-provider-validator
    app.kubernetes.io/name: swim-ed254-provider-validator
    app.kubernetes.io/part-of: swim-operator
spec:
  selector:
    matchLabels:
      app: swim-ed254-provider-validator
  endpoints:
  - port: http
    path: /q/metrics
    interval: 30s
    scrapeTimeout: 10s
